//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllTheBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AllTheBook()
        {
            this.BooksIssueds = new HashSet<BooksIssued>();
        }
    
        public int BookID_PK { get; set; }
        public string Name { get; set; }
        public Nullable<int> AuthorID_FK { get; set; }
        public string Description { get; set; }
        public Nullable<int> PublisherID_FK { get; set; }
        public long ISBN { get; set; }
        public Nullable<int> PrintLength { get; set; }
        public Nullable<int> InterestedAge { get; set; }
        public Nullable<int> CategoryID_FK { get; set; }
        public string Image { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BooksIssued> BooksIssueds { get; set; }
    }
}
