//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksIssued
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BooksIssued()
        {
            this.Fines = new HashSet<Fine>();
        }
    
        public int IssuedID_PK { get; set; }
        public Nullable<int> StudentID_FK { get; set; }
        public Nullable<int> StaffID_FK { get; set; }
        public Nullable<int> IssusedID_FK { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string Status { get; set; }
    
        public virtual AllTheBook AllTheBook { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fine> Fines { get; set; }
    }
}
