//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int FineID_PK { get; set; }
        public Nullable<int> StudentID_FK { get; set; }
        public Nullable<int> StaffID_FK { get; set; }
        public string Description { get; set; }
        public Nullable<int> SeverityOfFine { get; set; }
        public int WhatBookWasIssued { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Student Student { get; set; }
        public virtual BooksIssued BooksIssued { get; set; }
    }
}
